site:
    title: 'Michal Zimmermann'
    description: 'Pieces of knowledge from the world of GIS.'
    author: Michal Zimmermann
    category_url: category/%category%
    hide_quickstart: true
    pretty_urls: true
    posts_per_page: 10
    post_url: %year%/%slug%
    enable_gzip: true
    tag_url: tag/%tag%
    trailing_slash: true
smartypants:
    enable: true
